#ifndef __ARCH_BOARD_BOARD_H
#define __ARCH_BOARD_BOARD_H

#include <nuttx/config.h>
#ifndef __ASSEMBLY__
# include <stdint.h>
#endif

#include <stm32.h>

/* Clocking — STM32F407 demo board, 8 MHz HSE, 168 MHz SYSCLK. */

#define STM32_BOARD_XTAL        8000000ul

#define STM32_HSI_FREQUENCY     16000000ul
#define STM32_LSI_FREQUENCY     32000
#define STM32_HSE_FREQUENCY     STM32_BOARD_XTAL

#define STM32_PLLCFG_PLLM       RCC_PLLCFG_PLLM(8)
#define STM32_PLLCFG_PLLN       RCC_PLLCFG_PLLN(336)
#define STM32_PLLCFG_PLLP       RCC_PLLCFG_PLLP_2
#define STM32_PLLCFG_PLLQ       RCC_PLLCFG_PLLQ(7)

#define STM32_SYSCLK_FREQUENCY  168000000ul

#define STM32_RCC_CFGR_HPRE     RCC_CFGR_HPRE_SYSCLK
#define STM32_HCLK_FREQUENCY    STM32_SYSCLK_FREQUENCY
#define STM32_BOARD_HCLK        STM32_HCLK_FREQUENCY

#define STM32_RCC_CFGR_PPRE1    RCC_CFGR_PPRE1_HCLKd4
#define STM32_PCLK1_FREQUENCY   (STM32_HCLK_FREQUENCY / 4)

#define STM32_APB1_TIM4_CLKIN   (2 * STM32_PCLK1_FREQUENCY)
#define BOARD_TIM4_FREQUENCY    STM32_APB1_TIM4_CLKIN

#define STM32_RCC_CFGR_PPRE2    RCC_CFGR_PPRE2_HCLKd2
#define STM32_PCLK2_FREQUENCY   (STM32_HCLK_FREQUENCY / 2)

/* USART3 — serial console (CONFIG_STM32_USART3). */

#define GPIO_USART3_RX          GPIO_USART3_RX_3
#define GPIO_USART3_TX          GPIO_USART3_TX_3

/* GPIO outputs — PA5 demo LED (CONFIG_DEV_GPIO). */

#define BOARD_GPIO_DEMO_LED       (GPIO_OUTPUT | GPIO_PUSHPULL | GPIO_SPEED_50MHz | GPIO_OUTPUT_CLEAR | GPIO_PORTA | GPIO_PIN5)
#define TAROX_GPIO_DEMO_LED         "/dev/demo_led"

/* PWM outputs — TIM4 CH2 on PD13 (CONFIG_STM32_TIM4_PWM). */

#define BOARD_PWM_DEMO_TIMER      4
#define BOARD_PWM_DEMO_CHANNEL    2
#define GPIO_TIM4_CH2OUT          GPIO_TIM4_CH2OUT_2
#define BOARD_PWM_DEMO_GPIO       GPIO_TIM4_CH2OUT
#define TAROX_PWM_DEMO              "/dev/demo_pwm"

#endif /* __ARCH_BOARD_BOARD_H */
